default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: emmortal_development

test:
  <<: *default
  database: emmortal_test

staging:
  <<: *default
  database: emmortal

production:
  <<: *default
  database: emmortal
